#!/bin/bash

# tap email
adb shell input tap 1000 600

# clear everything
adb shell input keyevent 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67 67

testEmail="x@y.z"

adb shell input text $testEmail

adb shell input keyevent 66

sleep 1

adb shell input text test1234

adb shell input keyevent 66

# 1 -->  "KEYCODE_MENU" 
# 3 -->  "KEYCODE_HOME" 
# 4 -->  "KEYCODE_BACK"  
# 28 -->  "KEYCODE_CLEAR" 
# 61 -->  "KEYCODE_TAB" 
# 62 -->  "KEYCODE_SPACE" 
# 66 -->  "KEYCODE_ENTER" 
# 67 -->  "KEYCODE_DEL" 