#!/bin/bash

xcode_key_plist="/Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Resources/IDETextKeyBindingSet.plist"
sudo chmod 666 ${xcode_key_plist}
sudo chmod 777 /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Resources/

plutil -replace "Insertions and Indentations"."Duplicate current line" -string "selectLine:, copy:, moveToBeginningOfLine:, paste:" ${xcode_key_plist} 
plutil -replace "Deletions"."Deletions" -string "selectLine:, copy:, moveToBeginningOfLine:, paste:" ${xcode_key_plist} 


